### ISSUE TITLE
WindowsPhone store binary error. 

### ISSUE THREAD

**Issue by PrakashPraki** [pinger-inc/FFMPEG_WindowsPhone#3]
I am using FFMPEG runtime in my windows phone project. I am facing this error when i am submitting xap to windows phone store .
"The native API api-ms-win-core-processthreads-l1-1-1.dll:GetProcessTimes() isn’t allowed in assembly FFMPEGRuntime.dll. Update it and then try again."

I don't know how to resolve this error . Please help me.

**Comment by santhosh-kumar** [comment]
We checked-in new debug and release ffmpeg.lib without GetProcessTimes. Here is the patch: https://github.com/pinger-inc/FFMPEG_WindowsPhone/commit/2d2752dd511d9d407fdbaf9e5a9b2d7898e5ec7d

**Comment by PrakashPraki** [comment]
Thank you.

**Comment by PrakashPraki** [comment]
Thank you again, now windows phone store does not report any issue!

**Comment by ghost** [comment]
Hi santhosh-kumar,

Thanks for wonderful library. After update newest ffmpeg.lib from github (include remove getprocesstimes), I try to build a testing project using FFMPEGRuntime and upload to store but still get error with message:
Package acceptance validation error: The native API api-ms-win-core-processthreads-l1-1-1.dll:GetProcessTimes() isn’t allowed in assembly FFMPEGRuntime.dll. Update it and then try again.

The ffmpeg.lib which i downloaded, you can see here: http://i.imgur.com/LeUI1p5.png
Does any special configs for this lib work? I build release, clean & rebuild.
Could you give me a sample project that can upload to the store without this error?

Thanks in advance,
ZNToan
