### ISSUE TITLE
Requested Windows Runtime type 'FFMPEGRuntime.FFMpeg' is not registered.

### ISSUE THREAD

**Issue by prabhuravi** [pinger-inc/FFMPEG_WindowsPhone#4]
Hi, Added new ffmpeg.lib after removing getProcesstimes but i get a run-time error Requested Windows Runtime type 'FFMPEGRuntime.FFMpeg' is not registered. please help. Thanks in advance

**Comment by santhosh-kumar** [comment]
Not sure about the exact problem, may be this is helpful: https://social.msdn.microsoft.com/forums/windowsapps/en-us/f852372d-cd1f-47e8-992a-715aff8904a4/problems-creating-winrt-component-dll

If you had renamed any of the components.

**Comment by ghost** [comment]
Hi santhosh-kumar,

I retarget your sample project to Windows Phone 8.1, build success but when i'm record & press "convert" the error: No URL Protocols are registered. Missing call to av_register_all()

Any suggestion for me? Can we run ffmpeg on WP8.1 silverlight?

**Comment by santhosh-kumar** [comment]
Try this: http://stackoverflow.com/questions/9882043/ffmpeg-av-register-all-not-working
