### ISSUE TITLE
Unable to Find ffmpeg.lib file when compiled

### ISSUE THREAD

**Issue by prabhuravi** [pinger-inc/FFMPEG_WindowsPhone#5]
I have followed your instruction and was able to compile , but however i just got the following Lib files
avcodec
avdevice
avfilter
avformat
avresample
avutil
postproc
swresample
swscale
i find the  ffmpeg.lib file missing.

**Comment by santhosh-kumar** [comment]
On a successful build, ffmpeg.lib should be available in the build/Debug or build/release folder. Please check whether the build actually succeeded. 

We have already checked-in all the libraries. Please run the demo app and try it again.

**Comment by prabhuravi** [comment]
I checked with the demo app, and it fails the store test. 
![Uploading ffmpeg.JPG…]()

**Comment by prabhuravi** [comment]
![ffmpeg](https://cloud.githubusercontent.com/assets/12391061/7580626/64c77624-f896-11e4-89c5-5cea3dc7d477.JPG)
I checked with the demo app, and it fails the store test.

**Comment by santhosh-kumar** [comment]
Thanks for the report. Demo app is not store-compliant, it is only for a guideline. We had updated the ffmpeg.lib last week to fix the GetProcessTimes issue.

**Comment by prabhuravi** [comment]
yes, i have updated the latest ffmpeg.lib, (release version) and recompiled the FFMPEGruntime and then referred FFMPEGRuntime.winmd from .\FFMPEGRuntime\ARM\Release\FFMPEGRuntime. but still it fails in store test. I have completed my app using FFMPEG but then i am not able to submit to store.  Can u please help me on this. ? Thanks in advance.

**Comment by prabhuravi** [comment]
Also will be helpful if you could provide a  store-compliant version of  FFMPEGRuntime.winmd  and FFMPEGRuntime.dll . Thanks!

**Comment by santhosh-kumar** [comment]
We are not sure about the other error that you are running into w.r.t. CreateThread method (we haven't encountered). Here is the dropbox link to FFMPEGRuntime.dll and winmd files that you requested (https://www.dropbox.com/s/y6m5twctreybw0h/ARM.zip?dl=0)

Note: Other users were able to submit their apps using this project (https://github.com/pinger-inc/FFMPEG_WindowsPhone/issues/3). Also, we don't plan to release the demo app to the store at this point of time. We will create a bug/feature request if someone in the community is willing to fix this problem.

**Comment by PrakashPraki** [comment]
thank you so much for sending the release and debug folders, that was helpful! :)

I loaded this in the demo project and verified in visual studio. One error disappeared and the other about the CreateThread remains.

Thanks for your time!

![only 1 error now](https://cloud.githubusercontent.com/assets/12293386/7618263/86368c4e-f9ce-11e4-9cb3-09da249d1461.png)

**Comment by PrakashPraki** [comment]
Also I spent the whole day and managed to compile it how the ffmpeg.lib is not being generated, can you please provide the configure command you are using?

I tried with the build script on repo as well. No luck.

Thank you very much for your guidance on this.

**Comment by santhosh-kumar** [comment]
Please note that this is a Windows Phone project. According to:

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/1f9e87d1-934c-41e8-8bd3-f115c16183f5/createthread-function-in-windows-81-phone-applications?forum=wpdevelop

Windows Store Apps does not support CreateThread. As mentioned in build steps, We invoke:

./build_ffmpeg_msvc.sh to configure and build the app.

**Comment by santhosh-kumar** [comment]
Here is the output configure that is generated: https://www.dropbox.com/s/jumymwl9hhhwwdr/configure.zip?dl=0

**Comment by PrakashPraki** [comment]
Ok thanks.

Also we are actually trying this for a Windows Phone project NOT for a windows store app.

**Comment by prabhuravi** [comment]
The  output configure file you gave worked! it passed the store test! Thanks for your time for us.

**Comment by ghost** [comment]
Hi 

The link https://www.dropbox.com/s/jumymwl9hhhwwdr/configure.zip?dl=0 was broken :(
Could you please upload this file again?

Thanks.

**Comment by santhosh-kumar** [comment]
Please check this: https://www.dropbox.com/s/jumymwl9hhhwwdr/configure.zip?dl=0

Hope it helps!

**Comment by ghost** [comment]
When I follow your instruction (github), after long time wating for building, i get this error and process was interrupted.

![untitled2](https://cloud.githubusercontent.com/assets/5864798/9053773/d7552ad4-3aa3-11e5-9dbc-d4ef4f31ebba.png)

I don't know how to resolve this, could you help me?

**Comment by santhosh-kumar** [comment]
I am not sure about the error you are getting. Search for these files in your ffmpeg project folder, you may  have these files built but failed to copy:

avcodec.lib
avdevice.lib
avfilter.lib
avformat.lib
avresample.lib
avutil.lib
ffmpeg.lib  
postproc.lib
swresample.lib  
swscale.lib

**Comment by ghost** [comment]
Thanks for quick reply!
You are right, I have been seaching for these files & found some of them, each lib locate in each special folder. But I can not find:
- avutil.lib
- ffmpeg.lib
  I think these files fail to build. Do you have any suggestion for me?

**Comment by santhosh-kumar** [comment]
I am not sure what's the problem. It could be due to Visual Studio 2012 configuration. Did you try pre-built libraries (release or debug)? prabhuravi seems to have luck using it.

**Comment by ghost** [comment]
Could I know the environment that you use to build these libs such as Windows version, 32 or 64 bit?
Pre-build, Currently i'm using debug mode (./build_ffmpeg_msvc.sh).

**Comment by santhosh-kumar** [comment]
Check this out: https://www.dropbox.com/sh/4get43v5ir2bur2/AAA5jxK7MZvHt6FvMe159Y3Wa?dl=0

I have added my system info and visual studio info.

**Comment by ghost** [comment]
I see. Let's me try with Windows 8 (I using Windows 8.1). Thanks for your wonderful support!

**Comment by ghost** [comment]
Hi santhosh-kumar,

Now i can build the libs without error but when using them (replace prev libs from you on github) i run into a lot of error, you can see bellow.
![untitled](https://cloud.githubusercontent.com/assets/5864798/9092228/01a5c768-3bcf-11e5-977e-8c68a35a9903.png)
Any special configs that make it work?

**Comment by santhosh-kumar** [comment]
This seems to be a problem in Visual Studio Configuration or the VS version. It is complaining that it cannot find some math functions. You could check the config header in ffmpeg and enable FFMPEG's implementation of those functions. I am not sure whether that would be the end of it.... Good luck.

**Comment by ankitsiliconithub** [comment]
![Uploading Screen Shot 2016-09-14 at 12.18.00 AM.png…]()
Hi

The link https://www.dropbox.com/s/jumymwl9hhhwwdr/configure.zip?dl=0 was broken :(
Could you please upload this file again?

i have error when upload app my project was almost done because of error i m faced too much issue please help me.

Thanks.
