### ISSUE TITLE
Make the demo app store compliant

### ISSUE THREAD

**Issue by santhosh-kumar** [pinger-inc/FFMPEG_WindowsPhone#6]
Some users reported that they had issues submitting their app to the windows phone store. 

![64c77624-f896-11e4-89c5-5cea3dc7d477](https://cloud.githubusercontent.com/assets/7297558/7616558/221ec95c-f95a-11e4-99f7-e21faf2767ec.JPG)

**Comment by prabhuravi** [comment]
After removing the GetProcessTimes() , the CreateThread() still showed in store test kit, but how ever this didnt not show up in when we submit to windows phone app store. I guess we can use the latest builds for windows phone app and it is store compliant . Thanks!
